### ISSUE TITLE
notify by email-html does not work

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-notifications#15] opened 2017-08-01 18:31 UTC
notify by email-html is configured and does work from shell, why is notify by slack used by alignak for it?

```
[alignak.scheduler] The notification command '/usr/local/var/libexec/alignak/notify_by_slack.py
[alignak.action] Action '/usr/local/var/libexec/alignak/notify_by_slack.py -n service -c "PROBLEM,,localhost,,127.0.0.1,,Tue 01 Aug 19:07:10 CEST 2017" ...
```

```
# -----------------------------------------------------------------------------
# user notificationways is empty "[ (0) ]"!
#
# alignak-backend-cli get -l -f /tmp -t user
# jsonfui /tmp/alignak-object-list-users.json

_id                           "5960e4dfa9fb6e2a161860b8"
_is_template                  false
_realm                        "5960c728a9fb6e29fa185a69"
_sub_realm                    true
_template_fields              { ... }
_templates                    [ (1) ]
address1                      "none"
address2                      "none"
address3                      "none"
address4                      "none"
address5                      "none"
address6                      "none"
alias                         "Administrator"
back_role_super_admin         false
can_submit_commands           true
can_update_livestate          false
customs                       { ... }
definition_order              100
email                         "admin@dummy.de"
host_notification_commands    [ (1) ]
host_notification_options     [ (5) ]
host_notification_period      "5960c728a9fb6e29fa185a6d"
host_notifications_enabled    true
imported_from                 "alignak-backend-import"
is_admin                      true
min_business_impact           1
name                          "imported_admin"
notes                         ""
notificationways              [ (0) ]
pager                         "0600000000"
password                      "pbkdf2:sha1:1000$urYGf34404"
service_notification_commands [ (1) ]
service_notification_options  [ (6) ]
service_notification_period   "5960c728a9fb6e29fa185a6d"
service_notifications_enabled true
skill_level                   0
tags                          [ (0) ]
token                         "1499522...023"
ui_preferences                { ... }
```

```
# -----------------------------------------------------------------------------
define host{
name                    generic-host
...
notifications_enabled   1
contact_groups          admins
...
}

# -----------------------------------------------------------------------------
define service{
...
name                    generic-service
contact_groups          admins
...
}

# -----------------------------------------------------------------------------
define contact{
name                            generic-contact
host_notifications_enabled      1
service_notifications_enabled   1
email                           alignak@localhost
can_submit_commands             1
# notificationways                email
notificationways                email-html
register                        0
}

# -----------------------------------------------------------------------------
define contactgroup{
contactgroup_name   admins
alias               admins
members             admin
}

# -----------------------------------------------------------------------------
# /usr/local/etc/alignak/arbiter/objects/contacts/admin.cfg
define contact{
use                 generic-contact
contact_name        admin
alias               Administrator
email               admin@dummy.de
pager               0600000000
password            admin
is_admin            1
can_submit_commands 1   ; Implicit because it is an admin
}
```

```
# -----------------------------------------------------------------------------
# alignak: develop
Date:   Tue Aug 1 09:12:07 2017 +0200
c05884e687385e40b56aeca0667bc63d1f46c074
Author: Frédéric MOHIER <frederic.mohier@gmail.com>

# -----------------------------------------------------------------------------
# alignak-backend: develop
Date:   Tue Aug 1 09:26:14 2017 +0200
530f7afef74071bc449d5629669571a25db02f54
Author: David Durieux <ddurieux@users.noreply.github.com>

# -----------------------------------------------------------------------------
# alignak-backend-client: develop
Date:   Tue Aug 1 09:05:54 2017 +0200
239984bddf2ea5b6d58d8ffcefd884dc985f7116
Author: Frédéric MOHIER <frederic.mohier@gmail.com>

# -----------------------------------------------------------------------------
# alignak-backend-import: develop
Date:   Fri Jun 23 05:22:12 2017 +0200
60a0d6114ca1d6b1319a68a0b50d8d42dc747eac
Author: Frédéric MOHIER <frederic.mohier@gmail.com>

# -----------------------------------------------------------------------------
# alignak-module-backend: develop+retention_put
Date:   Sun Jul 30 23:51:21 2017 +0200
4fd57a8b5b7fad26e5ea700357ca3a20f8b419bc
Author: David Durieux <d.durieux@siprossii.com>

# -----------------------------------------------------------------------------
# alignak-module-external-commands: updates
Date:   Mon Mar 13 15:50:46 2017 +0100
af957fbcf54112079f721d67db882b1e6da1ae48
Author: Frédéric MOHIER <frederic.mohier@gmail.com>

# -----------------------------------------------------------------------------
# alignak-module-logs: develop
Date:   Sun Jul 30 13:44:49 2017 +0200
3ce59f48c0fc632c4718a11a9152efc8fb960052
Author: Frédéric MOHIER <frederic.mohier@gmail.com>

# -----------------------------------------------------------------------------
# alignak-module-ws: develop
Date:   Sun Jul 30 13:59:48 2017 +0200
20f4160aa72a8966739a5ee71a45dee2807db87e
Author: Frédéric MOHIER <frederic.mohier@gmail.com>

# -----------------------------------------------------------------------------
# alignak-notifications: develop
Date:   Mon Jul 31 10:34:33 2017 +0200
ea49baef79ad8df4b64258957b43b19fa8decfc5
Author: David Durieux <ddurieux@users.noreply.github.com>

# -----------------------------------------------------------------------------
# alignak-webui: develop
Date:   Tue Aug 1 10:30:37 2017 +0200
fd7348951e46763dcd06cb673a6b01f6894efe4e
Author: Frédéric MOHIER <frederic.mohier@gmail.com>
```

**Comment by spea1** [comment] 2017-08-01 19:19
I found in alignak two administrator users:
1. alias "Administrator" with name "admin" without email and without host_notification_commands and service_notification_commands
2. alias "Administrator" with name "**imported_admin**" with email and with host_notification_commands and service_notification_commands

```
# -----------------------------------------------------------------------------
# imported_admin: host_notification_commands: "5980b233a9fb6e6269deada3" 

_id                       "5980b233a9fb6e6269deada3"
_realm                    "5960c728a9fb6e29fa185a69"
_sub_realm                true
alias                     ""
command_line              "$PLUGINSDIR$/notify_by_slack.py -n host -c "$NOTIFICATIONTYPE$,,$HOSTNAME$,,$HOSTADDRESS$,,$LONGDATETIME$" -o "$HOSTSTATE$,,$HOSTDURAT...
definition_order          100
enable_environment_macros false
imported_from             "alignak-backend-import"
module_type               "fork"
name                      "notify-host-by-slack"
notes                     ""
poller_tag                "None"
reactionner_tag           "None"
timeout                   -1

```

```
# -----------------------------------------------------------------------------
# imported_admin: service_notification_commands: "5980b232a9fb6e6267dead9e"

_id                       "5980b232a9fb6e6267dead9e"
_realm                    "5960c728a9fb6e29fa185a69"
_sub_realm                true
alias                     ""
command_line              "$PLUGINSDIR$/notify_by_slack.py -n service -c "$NOTIFICATIONTYPE$,,$HOSTNAME$,,$HOSTADDRESS$,,$LONGDATETIME$" -o "$SERVICEDESC$,,$SERV...
definition_order          100
enable_environment_macros false
imported_from             "alignak-backend-import"
module_type               "fork"
name                      "notify-service-by-slack"
notes                     ""
poller_tag                "None"
reactionner_tag           "None"
timeout                   -1
```

**Therefore the notifies by e-mail html does not work.**

**Comment by mohierf** [comment] 2017-08-02 06:41
Hi @spea1 
1/ why two admin users? Because the Alignak backend creates an `admin` user that is the real big boss of the whole system. This user is set as super-administrator. When you are importing your configuration in the backend, if an `admin` user exists in this configuration his name is replaced with `importedf_admin` to avoid conflicting with the existing backend `admin` user ...

 2/ the default backend `admin` user is configured without any notifications

3/ the `notify-service-by-slack` command is a not yet tested script in the alignak-notifications package ... and perharps it exists in the imported configuration?

**Comment by spea1** [comment] 2017-08-06 09:42
notificationways: email-html

The "*_notification_commands" mapping to the user works according to luck and random logarithm.
It does not matter whether the scripts function. 
The commands are defined and it is not assigned to the user what I have defined "email-html".

```
/usr/local/etc/alignak/arbiter/templates/generic-contact.cfg                                                                    353/353               100%
# Contact definition
# By default the contact will ask notification by mails
define contact{
        name                            generic-contact
        host_notifications_enabled      1
        service_notifications_enabled   1
        email                           alignak@localhost
        can_submit_commands             1
        notificationways                email-html
        register                        0
        }
```

Test Import 1
```
    },
        "_id": "5986decaa9fb6e7f170e3dc2",
        "_realm": "5986deb8a9fb6e7f010e3da1",
        "_sub_realm": true,
        "alias": "",
        "command_line": "$PLUGINSDIR$/notify_by_xmpp.py -a $PLUGINSDIR$/notify_by_xmpp.ini \"Host '$HOSTNAME$' is $HOSTSTATE$ - Info : $HOSTOUTPUT$\" $CON
        "definition_order": 100,
        "enable_environment_macros": false,
        "imported_from": "alignak-backend-import",
        "module_type": "fork",
        "name": "notify-host-by-xmpp",
        "notes": "",
        "poller_tag": "None",
        "reactionner_tag": "None",
        "timeout": -1
    },
```

Test Import X
```
    {
        "_id": "5986e079a9fb6e0547345f3e",
        "_realm": "5986e053a9fb6e052c345f27",
        "_sub_realm": true,
        "alias": "",
        "command_line": "$PLUGINSDIR$/notify_by_slack.py -n host -c \"$NOTIFICATIONTYPE$,,$HOSTNAME$,,$HOSTADDRESS$,,$LONGDATETIME$\" -o \"$HOSTSTATE$,,$H
        "definition_order": 100,
        "enable_environment_macros": false,
        "imported_from": "alignak-backend-import",
        "module_type": "fork",
        "name": "notify-host-by-slack",
        "notes": "",
        "poller_tag": "None",
        "reactionner_tag": "None",
        "timeout": -1
    },
```

**Comment by mohierf** [comment] 2017-08-06 14:54
Would you please dump one of your contact for I understand clearly what the problem is? I do not have any problem with this ...

**Comment by mohierf** [comment] 2018-02-25 08:47
Closing this. @spea1 feel free to re-open and comment if needed.

**Closed by mohierf** 2018-02-25 08:47 UTC
